### PR TITLE
Apply project settings to o.e.equinox.http.servlet.tests

### PR DESCRIPTION
**Pull request by Torbjorn-Svensson**
1. Convert to LF and ensure LF at EOF:
```shell
find . -type f -print0 | \
  xargs -r0 perl -le 'for (@argv) { print if -f && -T }' | \
  xargs -rd'\n' dos2unix -e
```

2. Removed executable flag on files:
```shell
find . -type f -executable -print0 | \
  xargs -r0 chmod 644
```

3. Format java files:
```shell
eclipse -consolelog -nosplash -application org.eclipse.jdt.core.JavaCodeFormatter \
  -config .settings/org.eclipse.jdt.core.prefs . -data `mktemp -d`
```

### CODE REVIEW

**Comment by akurtakov** [comment]
This PR breaks tests https://ci.eclipse.org/equinox/job/equinox/job/PR-355/3/#showFailuresLink

**Comment by Torbjorn-Svensson** [comment]
> This PR breaks tests https://ci.eclipse.org/equinox/job/equinox/job/PR-355/3/#showFailuresLink

I think I fixed all the failures with the last push.
I have some trouble running the test suite locally as my target platform does not appear to have the required jetty/jasper dependencies, but with some tweaks, I managed to get the ServletTest running in junit.
Let me know if there is more I should address.

**Comment by Torbjorn-Svensson** [comment]
Rebased PR on 1d9eb47f09654da0ed7c205fa2cf8e664b97c08b.
Anything I need to do prior to getting this merged?

**Comment by vogella** [comment]
@Torbjorn-Svensson this one has conflicts, please have a look

**Comment by Torbjorn-Svensson** [comment]
Something had went wrong in the last rebase so this PR accidentally included changes in another bundle. Corrected now and rebased on b297e0504c8a41cb336ab3739851c9edb9131e63.

**Pull request merged**
