### PR TITLE
Improve the output of the automatic JPMS generation

### PR DESCRIPTION
**Pull request by laeubi**
This is for further improving the work started at https://github.com/eclipse-equinox/equinox/pull/36.

### CODE REVIEW

**Comment by laeubi** [comment]
@rotty3000 we have an issue with the generated class see https://github.com/eclipse-equinox/equinox/issues/42 is it possible to adjust this?

**Comment by HannesWell** [comment]
Btw. couldn't we use the `bnd-process` goal with an bnd element in the `bnd-maven-plugin` configuration that contains the content of the `bnd.bnd` file, just like we do it in m2e?
https://github.com/eclipse-m2e/m2e-core/blob/4c1f0dc8667f4e0a4e3f6871b9b0e3d91a6e7ac2/m2e-maven-runtime/pom.xml#L61

This would save us the extra bnd.bnd file.

**Comment by laeubi** [comment]
> This would save us the extra bnd.bnd file.

An require us to embedd non XML data into XML ;-)

beside that, my goal is more to get rid of the pom here after the next tycho release...

**Comment by laeubi** [comment]
@tjwatson I'm not sure about the state of this, do you plan to take a look or should we close this?

**Comment by akurtakov** [comment]
Looks like it's good enough so closing. @tjwatson can reopen/push it if still needed.

**Pull request closed without merging**
