### PR TITLE
Ignore j9stubs in module-info generation

### PR DESCRIPTION
**Pull request by fipro78**

### CODE REVIEW

**Comment by tjwatson** [comment]
Fixes #274

@fipro78 have you been able to confirm this fixes your issue?

**Comment by fipro78** [comment]
@tjwatson
Can I download the build results of the PR build somewhere? Or do I need to build it locally?

**Comment by fipro78** [comment]
I tried to build locally with my changes, but I get strange errors. Maybe because I am behind a corporate proxy. The error message is:

```
Failed to resolve target definition file:/C:/Users/xxx/.m2/repository/org/eclipse/eclipse-sdk-prereqs/4.29.0-SNAPSHOT/eclipse-sdk-prereqs-4.29.0-SNAPSHOT.target: Failed to load p2 metadata repository from location https://download.eclipse.org/tools/orbit/downloads/drops/R20201118194144/repository/: Unable to read repository at https://download.eclipse.org/tools/orbit/downloads/drops/R20201118194144/repository. ConnectException: UnresolvedAddressException
```

I tried to configure a local mirror in my settings.xml like this:

```
   <mirror>
	  <id>orbit202305-local</id>
	  <mirrorOf>https://download.eclipse.org/tools/orbit/downloads/drops/R20230531010532/repository</mirrorOf>
	  <url>file:///C:/Development/update-sites/orbit-202305/</url>
	  <layout>p2</layout>
	  <mirrorOfLayouts>p2</mirrorOfLayouts>
   </mirror>
```

But the mirror doesn't seem to be used. I checked the target file that is downloaded in the local maven repository, and there I see a trailing slash in the repository location. The [Tycho docs](https://wiki.eclipse.org/Tycho/Target_Platform/Authentication_and_Mirrors) say, there should be no trailing slash.

@laeubi Do you have any idea on this? You are the Tycho expert. :)

Sorry for hijacking this topic. This is of course not related to the issue. It just brings me back to my question if it is possible to download the build results of the CI build, so I can check if my changes solved the issue, as I am currently not able to build locally.

**Comment by laeubi** [comment]
`UnresolvedAddressException` looks strange, nerveless mirroring should work that way, if I remember correctly Tycho should print a message like "Using mirror for ..." if the mirror is found, here is an example with multiple mirrors defined:

https://github.com/faktorips/faktorips.base/blob/main/settings.xml

if the settings.xml is not at default location you need to specify it with `-s` option to maven.

**Comment by fipro78** [comment]
The settings.xml is at the default location.

The info message before the failure is the following:

```
[INFO] Loading repository '' from mirror 'orbit202305-local' at 'file:///C:/Development/update-sites/orbit-202305/'
[INFO] ### Using TychoRepositoryTransport for remote P2 access ###
[INFO]     Cache location:         C:\Users\fad8pl\.m2\repository\.cache\tycho
[INFO]     Transport mode:         online
[INFO]     Http Transport type:    Java11Client
[INFO]     Update mode:            cache first
[INFO]     Minimum cache duration: 60 minutes
[INFO]       (you can configure this with -Dtycho.p2.transport.min-cache-minutes=<desired minimum cache duration>)
[INFO] Downloading from p2: https://download.eclipse.org/tools/orbit/downloads/drops/R20201118194144/repository/p2.index
```

So something doesn't seem to work right. Where are the eclipse-sdk-prereqs come from? Maybe I could try to edit the .target file and remove the trailing slash from the location. IIRC that solved the issue in the past in my setups.

**Comment by laeubi** [comment]
> So something doesn't seem to work right. Where are the eclipse-sdk-prereqs come from? Maybe I could try to edit the .target file and remove the trailing slash from the location. IIRC that solved the issue in the past in my setups.

The sources are here:
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/tree/master/eclipse.platform.releng.prereqs.sdk

please don't hesitate to open a bugreport at Tycho if its just a matter of stripping the slash we should fix that (there are already some mirror tests but seem they are not covering that at the moment) or suggest changes to that file.

**Comment by fipro78** [comment]
@laeubi I created https://github.com/eclipse-tycho/tycho/issues/2533 to track the issue.

@tjwatson I will try to build at home from my private machine later, so I can verify the changes from a local build.

**Comment by laeubi** [comment]
@fipro78 just to make sure, you need to bump the micro version of the bundle otherwise your changes will be replaced with the baseline!

**Comment by fipro78** [comment]
@laeubi 
Thanks for the pointer. You are right, after I updated locally to 3.18.600 the resulting org.eclipse.osgi bundle works again on the module path.

Should I update the version? It is already 3.18.500. So wasn't it updated already?

**Comment by laeubi** [comment]
It should be updated for each change in a release, I'm not aware of any updates in this release, but I think @tjwatson can tell better here.

**Comment by tjwatson** [comment]
> It should be updated for each change in a release,

We have always only updated the micro-version once each release.

> I'm not aware of any updates in this release, but I think @tjwatson can tell better here.

The `org.eclipse.osgi` project version has already been updated with 044487a5a6e4457cd2ec9795a4a123ba6b9d0eea

**Comment by tjwatson** [comment]
> Thanks for the pointer. You are right, after I updated locally to 3.18.600 the resulting org.eclipse.osgi bundle works again on the module path.

I'm not sure why you needed to do that unless it was comparing to the last time you built it locally and you already had the version bump.

I merged the fix.  Thanks for confirming it fixed your problem.

**Pull request merged**
