### PR TITLE
use stronger cipher for secure storage

### PR DESCRIPTION
**Pull request by gireeshpunathil**
move the default from weaker MD5/DES to a stronger SHA/AES which is available in JVMs.
PBEWithMD5AndDES -> PBEWithHmacSHA512AndAES_256

### CODE REVIEW

**Comment by gireeshpunathil** [comment]
tests did not fail when ran locally, but 2 failed here, not sure why. are those known issues?

**Comment by akurtakov** [comment]
The failures look caused by the patch as I don't remember seeing these failing . 
Tests run on linux so that could be one reason why you dont see it locally if you run on other OS.

**Comment by gireeshpunathil** [comment]
thanks @akurtakov - I will investigate.

**Comment by gireeshpunathil** [comment]
The decrypt was throwing different error code with the new cipher.
old: `Input length must be multiple of 8 when decrypting with padded cipher`, (code:3)
new: `Wrong parameter type: IV expected`, (code: 0)

So I adjusted the test to accommodate the new scenario.

**Review by tjwatson — COMMENTED** [review]
We need micro-version increases to the bundles.  Otherwise looks good to me.

**Review by tjwatson — APPROVED** [review]

**Comment by tjwatson** [comment]
> @tjwatson - just pushed a change to up the bundle versions, PTAL. thanks!
Thanks, I merged it.

**Comment by iloveeclipse** [comment]
FYI, this was one from the root causes of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1388.

**Comment by gireeshpunathil** [comment]
thanks @iloveeclipse for catching this!

**Pull request merged**
