### PR TITLE
improve Dark Theme on Windows eclipse-platform/.github#27

### PR DESCRIPTION
**Pull request by betamaxbandit**
Using CTabFolder and CTabItem, instead of TabFolder/TabItem, improves the look when in Dark Theme; the background of the tab no longer has a non-dark background.

This relates to multiple commits to fix:

[Windows][Dark theme] Multiple preference pages use tab widgets, that are not dark theme aware eclipse-platform/.github#27

### CODE REVIEW

**Comment by betamaxbandit** [comment]
Note, project's Save Actions include "Format all lines", so a number of unrelated lines contain formatting changes.

**Comment by laeubi** [comment]
@jonahgraham @mickaelistria @akurtakov I think this clearly shows that the "bandaiding" do not work/scale well... We can't put a restriction on every eclipse plugin to use CTab(Folder) just to improve dark-mode users... That will effectively require deprecate usage of TabFolder in all Platform code and every plugin written for eclipse...

**Comment by jonahgraham** [comment]
> @jonahgraham @mickaelistria @akurtakov I think this clearly shows that the "bandaiding" do not work/scale well... We can't put a restriction on every eclipse plugin to use CTab(Folder) just to improve dark-mode users... That will effectively require deprecate usage of TabFolder in all Platform code and every plugin written for eclipse...

Please continue this discussion on https://github.com/eclipse-platform/.github/issues/27

**Review by laeubi — CHANGES_REQUESTED** [review]
Requires discussion at https://github.com/eclipse-platform/.github/issues/27

**Pull request closed without merging**
