### PR TITLE
Fix and testcase for issue 156

### PR DESCRIPTION
**Pull request by mwgmnn**
Fix and testcase for issue 156: Eclipse-Resolver: Comparison method violates its general contract

### CODE REVIEW

**Review by bjhargrave — APPROVED** [review]

**Comment by HannesWell** [comment]
You have to set the version of `org.eclipse.osgi.compatibility.state` to `1.2.800` in order to fix the build.

**Review by tjwatson — APPROVED** [review]

**Comment by tjwatson** [comment]
The jenkins build passed all the tests but then failed on some timeout on the end:

```
java.lang.InterruptedException
	at java.base/java.lang.Object.wait(Native Method)
	at java.base/java.lang.Object.wait(Object.java:219)
	at hudson.remoting.Request$1.get(Request.java:317)
	at hudson.remoting.Request$1.get(Request.java:240)
	at hudson.remoting.FutureAdapter.get(FutureAdapter.java:66)
	at hudson.FilePath.copyRecursiveTo(FilePath.java:2753)
	at jenkins.model.StandardArtifactManager.archive(StandardArtifactManager.java:73)
	at hudson.tasks.ArtifactArchiver.perform(ArtifactArchiver.java:258)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:101)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

This should not be related to the resolver fix.  I think we can merge.

**Comment by tjwatson** [comment]
Fixes #156

**Comment by mwgmnn** [comment]
Thanks a lot, i already thought i made a mistake, also for the DSTest/testCircularityHandling that did not pass...

**Comment by tjwatson** [comment]
> also for the DSTest/testCircularityHandling that did not pass...

yeah, that one fails on the github actions build consistently and we cannot seem to figure out why.  It passes reliably on the jenkins build test run.

**Pull request merged**
