### PR TITLE
Apply project settings o.e.osgi

### PR DESCRIPTION
**Pull request by Torbjorn-Svensson**
1. Convert to LF and ensure LF at EOF:
```shell
find . -type f -print0 | \
  xargs -r0 perl -le 'for (@argv) { print if -f && -T }' | \
  xargs -rd'\n' dos2unix -e && \
  git checkout src/org/osgi felix
```

2. Removed executable flag on files:
```shell
find . -type f -executable -print0 | \
  xargs -r0 chmod 644
```

3. Format java files:
```shell
eclipse -consolelog -nosplash -application org.eclipse.jdt.core.JavaCodeFormatter \
  -config .settings/org.eclipse.jdt.core.prefs . -data `mktemp -d` && \
  git checkout src/org/osgi felix
```

### CODE REVIEW

**Comment by Torbjorn-Svensson** [comment]
Updated PR in accordance with https://github.com/eclipse-equinox/equinox/pull/324#issuecomment-1748853543.

**Comment by akurtakov** [comment]
I'm leaving this one for @tjwatson to decide.

**Comment by tjwatson** [comment]
Correct me if I am wrong.  This isn't urgent to the current release.  I will hold off until 2024-03 when the dev branch opens up for the next release.

**Comment by Torbjorn-Svensson** [comment]
No, it's not urgent.

**Comment by vogella** [comment]
@Torbjorn-Svensson can you fix the conflicts?

**Comment by Torbjorn-Svensson** [comment]
> @Torbjorn-Svensson can you fix the conflicts?

Branch rebased on 965893686744e71e6503e6d434459120223e281b

**Comment by Torbjorn-Svensson** [comment]
Rebased PR on 1d9eb47f09654da0ed7c205fa2cf8e664b97c08b.
Anything I need to do prior to getting this merged?

**Comment by vogella** [comment]
Thanks @Torbjorn-Svensson

**Pull request merged**
