### PR TITLE
Enabling MacOS launcher artifacts testing in github workflows

### PR DESCRIPTION
**Pull request by umairsair**
Relates to https://github.com/eclipse-equinox/p2/issues/166

### CODE REVIEW

**Comment by umairsair** [comment]
@sravanlakkimsetti kindly review.. MacOS testing was the missing bit in github workflows from launcher perspective and I have added that.. no binary updates required because of this PR..

**Comment by sravanlakkimsetti** [comment]
@subyssurendran666 Can you please take a look at this one?

**Comment by laeubi** [comment]
I noticed on some PRs that the Build Equinox / build-launcher-mac64 is often failing see for example:
https://github.com/eclipse-equinox/equinox/actions/runs/7810176950/job/21303190211?pr=504

will this be fixed here as well?

**Comment by subyssurendran666** [comment]
Sure @sravanlakkimsetti

**Comment by laeubi** [comment]
@subyssurendran666  @sravanlakkimsetti can we please finish this? currently the mac build always fails and this seems to fix it.

As this only affects the github verification I would give +1 as PL for merging this even in freeze period if not @tjwatson has any concerns.

**Review by sravanlakkimsetti — APPROVED** [review]

**Comment by sravanlakkimsetti** [comment]
> I noticed on some PRs that the Build Equinox / build-launcher-mac64 is often failing see for example: https://github.com/eclipse-equinox/equinox/actions/runs/7810176950/job/21303190211?pr=504
> 
> will this be fixed here as well?

the fix for this is to remove this line https://github.com/eclipse-equinox/equinox/blob/841faf85aba5967de4f4de9ae6729536300dc7bf/features/org.eclipse.equinox.executable.feature/library/cocoa/build.sh#L101. This line copies built artifacts to binaries repo, which does not exist during the validation runs. This copying part is not there for windows and linux. We can safely remove this line.

For the code changes I approved this change.

**Review by sravanlakkimsetti — APPROVED** [review]

**Review by sravanlakkimsetti — APPROVED** [review]

**Pull request merged**
