### PR TITLE
Ensure that the JSP support works with newer dependencies

### PR DESCRIPTION
**Pull request by merks**
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1251

### CODE REVIEW

**Comment by merks** [comment]
@akurtakov 

I'm not sure who else might want to review this?   The "continuous-integration/jenkins/pr-head" build passed....

**Comment by akurtakov** [comment]
What is the reason to restrict jasper version to [9,10) ? It might be good to keep the current version in the range.

**Comment by merks** [comment]
> What is the reason to restrict jasper version to [9,10) ? It might be good to keep the current version in the range.

I did that originally the first time I made the changes, but this time around when I did the changes, I noticed that this initializer class is not in the older bundle:

image

**Comment by akurtakov** [comment]
That's good enough explanation. If/when you have the whole story with jsps working please merge this one together with the rest so we get less build issues.

**Comment by merks** [comment]
These are the outstanding changes.  Remove (replace) the references to org.apache.jasper.glassfish here:

image

image

image

image

image

I think I need to commit this PR before I do the above removals...

Locally the help system works without org.apache.jasper.glassfish in the installation:

image

**Pull request merged**
