### PR TITLE
Fix native code issue

### PR DESCRIPTION
**Pull request by tjwatson**
Fixes issue #236

### CODE REVIEW

**Comment by tjwatson** [comment]
@laeubi do you understand why the `Build Equinox / build (pull_request)` build is failing to build `org.eclipse.osgi.tests` with errors like this:
```
Error:  Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:4.0.0-SNAPSHOT:compile (default-compile) on project org.eclipse.osgi.tests: Compilation failure: Compilation failure: 
Error:  /home/runner/work/equinox/equinox/bundles/org.eclipse.osgi.tests/src/org/eclipse/osgi/tests/appadmin/FailedApp.java:[16] 
Error:  	import org.eclipse.equinox.app.IApplication;
Error:  	       ^^^^^^^^^^^^^^^^^^^^^^^
Error:  The import org.eclipse.equinox.app cannot be resolved
```
The jenkins build does not fail the same way.

**Comment by tjwatson** [comment]
@krooq This PR has been merged.  There should be a nightly build done this evening with the fix.  It would be good if you could test out the fix in your environment.

**Comment by krooq** [comment]
Thanks so much for jumping on this, and so quickly too!
Looks like the build is still failing.
Also I'm not really sure how to test this in my environment as it's a transitive dependency of something, it might be a little hard to for me to figure out how to get it to resolve the source version.. but I'll give it a go.

**Comment by tjwatson** [comment]
> Thanks so much for jumping on this, and so quickly too! Looks like the build is still failing. Also I'm not really sure how to test this in my environment as it's a transitive dependency of something, it might be a little hard to for me to figure out how to get it to resolve the source version.. but I'll give it a go.

https://download.eclipse.org/eclipse/downloads/drops4/I20230323-1800/ has the fix if you can download and use that Eclipse SDK with your set of bundles/plugins.

If that is difficult to do I think you could just overwrite your installation of `org.eclipse.osgi` located in the plugins folder with the version from this build and then run with -clean.

**Pull request merged**
