### PR TITLE
Replace content of o.e.osgi.services by osgi-bundles from Maven-Central

### PR DESCRIPTION
**Pull request by HannesWell**
_This PR was originally created as https://github.com/eclipse-equinox/equinox.framework/pull/44 and is now moved to this repository due to the merge of the equinox.framework and equinox.bundles repository._

---

As discussed in https://github.com/eclipse-equinox/equinox/issues/18, this replaces all possible embedded osgi-sources of `org.eclipse.osgi.services` by corresponding osgi-bundles from Maven-Central.

These are:

- org.osgi.service.cm
-  org.osgi.service.component
-  org.osgi.service.device
-  org.osgi.service.event
-  org.osgi.service.metatype
-  org.osgi.service.provisioning
-  org.osgi.service.upnp
-  org.osgi.service.useradmin
-  org.osgi.service.wireadmin

As a side effect this updates the versions of
- org.osgi.service.component.* 1.4.0 -> 1.5.0

To comply with the Eclipse deprecation/removal process the replaced packages are not removed entirely but their content is replaced by requiring and re-exporting the provided osgi-bundles from Maven-Central. Bundles that require-bundle `org.eclipse.osgi.services` directly continue to work.

### CODE REVIEW

**Review by tjwatson — APPROVED** [review]
Looks good.  Although I don't really know about the releng changes.  Not to say they are wrong.  Just that I don't know enough about it to know if it is correct.  I approve to allow progress.

**Comment by HannesWell** [comment]
> Looks good. Although I don't really know about the releng changes. Not to say they are wrong. Just that I don't know enough about it to know if it is correct. I approve to allow progress.

Great. Thank you.

Are you referring to the .target file I added with the third commit? The third commit was just a temporary addition to be able to test the staged felix.scr artifacts in this build before it was released to maven-central and included in the platform.aggregator target.
I will remove the third commit entirely before submitting this PR (and likely squash commit one and two).

**Comment by tjwatson** [comment]
> Are you referring to the .target file I added with the third commit?

Yes I just did not  realize it was a separate commit.

**Comment by HannesWell** [comment]
The org.eclipse.equinox.ds.tests.tbc.DSTest.testCircularityHandling  that failed in the GH-build did not fail on Jenkins and also not on the runs before (which used the staged artifacts that should be the same). Therefore I suspect that it is not a permanent issue. -> Submitting.

**Comment by laeubi** [comment]
See #25 it seems sometimes it fails and sometimes not...

**Comment by HannesWell** [comment]
> See #25 it seems sometimes it fails and sometimes not...

Good to know. Thanks!

**Pull request merged**
