### PR TITLE
Status: make more threadsafe

### PR DESCRIPTION
**Pull request by jukzi**
Members are not final but used across threads.

### CODE REVIEW

**Comment by jukzi** [comment]
There was an error that i cannot explain otherwise where a wrong "status" was read: https://github.com/eclipse-platform/eclipse.platform/pull/310#issuecomment-1377072070

**Comment by laeubi** [comment]
I think the main question is if status should be threadsafe for concurrent access and shared between different threads concurrently... So I would assume that a status object is constructed, initlized and maybe modified and the passed alon and is the never modified...

**Comment by laeubi** [comment]
By the way making it "volativle" does not makes is "more threadsafe.... that would only be relevant if different threads see different states, but still if one thread modifies two fileds another thread might see an intermediate state...

So I must confess changing code just for trial-and-error without any evidence that it helps seems not desirable.

**Comment by laeubi** [comment]
e.g. `org.eclipse.core.runtime.MultiStatus.add(IStatus)` is more likely a source where concurrency can cause issues but then **all** methods must be synchronized!

**Comment by laeubi** [comment]
Another one `org.eclipse.core.internal.databinding.BindingStatus.add(IStatus)` again, adding volatile won't help in any of those cases.

**Pull request merged**
