### PR TITLE
remove Exceptions not actually thrown

### PR DESCRIPTION
**Pull request by jukzi**
eliminates problem markers and dead code

### CODE REVIEW

**Comment by jukzi** [comment]
only unrelated TCK fails...

**Comment by jukzi** [comment]
jenkins says fixes 19
image

**Review by laeubi — APPROVED** [review]
It looks sane but I would give final word @tjwatson

**Comment by vogella** [comment]
> can any committer review/submit, please?

I can nominate you as committer, if you want. Clean-up work is usually simpler if you have write access.

**Comment by jukzi** [comment]
> I can nominate you as committer, if you want. Clean-up work is usually simpler if you have write access.

ok, please do so. But i won't do much more then cleanups. Regarding bugs i want to focus on other projects.

**Pull request merged**
