### PR TITLE
Remove ident ID value

### PR DESCRIPTION
**Pull request by tjwatson**

### CODE REVIEW

**Comment by iloveeclipse** [comment]
Link to the issue: https://github.com/eclipse-equinox/equinox/issues/399

**Comment by vogella** [comment]
PMC approved (in case you need that)

**Review by iloveeclipse — APPROVED** [review]

**Comment by HannesWell** [comment]
Thanks Tom.

Indeed I used EGit and had no issue with that.
I just copied the original sources from Maven-Central.

**Comment by iloveeclipse** [comment]
Unfortunately the SDK build failed, see  https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1534

**Comment by iloveeclipse** [comment]
@tjwatson: Is there any reason to keep .gitattributes that cause such confusion?
Should we remove the ident sections from https://github.com/eclipse-equinox/equinox/blob/master/.gitattributes?
See git manual: https://git-scm.com/docs/gitattributes#:~:text=ident,Id%24%20upon%20check-in.

**Comment by tjwatson** [comment]
> @tjwatson: Is there any reason to keep .gitattributes that cause such confusion?

We can consider removing the `ident` value from the `.gitattributes`.  It only is an issue for the osgi source we include in our repo since we don't use `$Id$` in `org.eclipse` source.  But it will mean we either checkin source that has the Id filled in or it will be blank.

**Comment by iloveeclipse** [comment]
> But it will mean we either checkin source that has the Id filled in or it will be blank.

What is the problem with blank id? It is comment anyway, and I doubt the commit hash is that important for the sources shipped with a specific bundle version.

**Comment by tjwatson** [comment]
> What is the problem with blank id? It is comment anyway, and I doubt the commit hash is that important for the sources shipped with a specific bundle version.

I'm not suggesting it is a problem, only that we have to decide.  In the past you could diff the equinox source with the osgi source repo and they would show no differences because the Id would get filled in correctly on checkout.  If we use a blank Id then the diff that I usually run to make sure I got the right source will show a difference.  In the end it is unfortunate that we have to work around a many year old bug in jGit.  This long running bug has simply got me use to never using eGit to commit anything, ever.

**Pull request merged**
