### PR TITLE
Fix NPE by RegistryFactory.getRegistry

### PR DESCRIPTION
**Pull request by laeubi**
`RegistryFactory.getRegistry` can return null, but the static methods to not check for null.

### CODE REVIEW

**Comment by laeubi** [comment]
@HannesWell Any idea why the `testCircularityHandling` fails?

**Comment by HannesWell** [comment]
> @HannesWell Any idea why the `testCircularityHandling` fails?

Not really but ist used to fail for some time already even before the detection of deadlocks was merged.
But it only fails in the GH build.
Unfortunately I cannot help further in vacation.

**Comment by HannesWell** [comment]
But the failure is likely not related to this change.

**Comment by akurtakov** [comment]
Should this one be pushed?

**Comment by akurtakov** [comment]
I don't see issue with preventing this NPE.

**Pull request merged**
