### PR TITLE
Switch Jetty to requires in feature.xml

### PR DESCRIPTION
**Pull request by akurtakov**
That should avoid having to touch the feature everytime Jetty version is
changed.

### CODE REVIEW

**Comment by akurtakov** [comment]
@sravanlakkimsetti Any reason no to go that path?

**Comment by merks** [comment]
Might this result in these being missing from the repository?  I'd test that to be sure that's not a problem like perhaps this one is  problem:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/365

**Comment by akurtakov** [comment]
Pushing this one and starting I-build - hopefully everything works that way.

**Comment by laeubi** [comment]
@akurtakov Thanks for trying this out! This should greatly simplify referencing non-reactor dependencies in features now!

**Pull request merged**
