### PR TITLE
Apply project settings to o.e.osgi.tests

### PR DESCRIPTION
**Pull request by Torbjorn-Svensson**
1. Convert to LF and ensure LF at EOF:
```shell
find . -type f -print0 | \
  xargs -r0 perl -le 'for (@argv) { print if -f && -T }' | \
  xargs -rd'\n' dos2unix -e
```

2. Removed executable flag on files:
```shell
find . -type f -executable -print0 | \
  xargs -r0 chmod 644
```

3. Format java files:
```shell
eclipse -consolelog -nosplash -application org.eclipse.jdt.core.JavaCodeFormatter \
  -config .settings/org.eclipse.jdt.core.prefs . -data `mktemp -d`
```

### CODE REVIEW

**Comment by Torbjorn-Svensson** [comment]
Rebased PR on 1d9eb47f09654da0ed7c205fa2cf8e664b97c08b.
Anything I need to do prior to getting this merged?

**Comment by vogella** [comment]
Conflicts, please have a look

**Comment by Torbjorn-Svensson** [comment]
Rebased on b297e0504c8a41cb336ab3739851c9edb9131e63.

**Comment by Torbjorn-Svensson** [comment]
Test failure should be fixed now.

**Comment by Torbjorn-Svensson** [comment]
> > Test failure should be fixed now.
> 
> What did you do to fix the tests?

I simply added a trim of the returned content when comparing to the expected number as the content has already been verified a few lines above and the only thing that is to be tested is that it's the correct number in the file.

The change was done here: https://github.com/eclipse-equinox/equinox/compare/f8d0a1c3be3a5db5b2bb9bd8a97eaec49f268119..13dabee294f6c8bb4212391f4a941db6789e04b1

**Comment by vogella** [comment]
Thanks @Torbjorn-Svensson

**Pull request merged**
